name: wedding_planner
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.1
  flutter_spinkit: ^4.1.1+1
  intl: ^0.16.0
  provider: ^3.1.0+1
  shared_preferences: ^0.5.6
  http: ^0.12.0+2
  url_launcher: ^5.2.2
  firebase_auth: ^0.15.3+1
  cloud_firestore: ^0.13.0+1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/welcome_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/3.jpeg
    - assets/images/4.jpeg
    - assets/images/5.jpeg
    - assets/images/alb_f.png
    - assets/images/alb_m.png
    - assets/images/calender.png
    - assets/images/budget.png
    - assets/images/back_ground.jpg
    - assets/images/sara_logo.png
    - assets/images/splash_screen.jpeg
    - assets/images/welcome_logo.png
    - assets/images/instagram-logo.png
    - assets/images/facebook.png
    - assets/images/global.png


  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Regular.otf
         - asset: assets/fonts/Montserrat-Hairline.otf
         - asset: assets/fonts/Montserrat-Light.otf
           weight: 700
     - family: Christmas
       fonts:
         - asset: assets/fonts/Christmas-Regular.ttf
           style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
